create user &&REPLICATION_USER identified by "temp_123" DEFAULT TABLESPACE &&DEFAULT_REPLICATION_TABLESPACE;
alter user &&REPLICATION_USER quota unlimited on &&DEFAULT_REPLICATION_TABLESPACE;
grant resource,create session to &&REPLICATION_USER CONTAINER=ALL;
grant select on v_$database to &&REPLICATION_USER CONTAINER=ALL;
grant select on v_$transaction to &&REPLICATION_USER CONTAINER=ALL;
grant select on v_$logmnr_contents to &&REPLICATION_USER CONTAINER=ALL;
grant select on gv_$transaction to &&REPLICATION_USER CONTAINER=ALL;
grant select on dba_users to &&REPLICATION_USER CONTAINER=ALL;
grant select on dba_tables to &&REPLICATION_USER CONTAINER=ALL;
grant select on DBA_LOG_GROUPS to &&REPLICATION_USER CONTAINER=ALL;
grant select on dba_constraints to &&REPLICATION_USER CONTAINER=ALL;
grant execute_catalog_role to &&REPLICATION_USER CONTAINER=ALL;
grant select_catalog_role to &&REPLICATION_USER CONTAINER=ALL;
grant create database link to &&REPLICATION_USER CONTAINER=ALL;
grant execute on DBMS_UTILITY to &&REPLICATION_USER CONTAINER=ALL;
grant execute on DBMS_LOGMNR to &&REPLICATION_USER CONTAINER=ALL;
grant alter any table to &&REPLICATION_USER CONTAINER=ALL;
grant select any table to &&REPLICATION_USER CONTAINER=ALL;
grant delete any table to &&REPLICATION_USER CONTAINER=ALL;
grant insert any table to &&REPLICATION_USER CONTAINER=ALL;
grant update any table to &&REPLICATION_USER CONTAINER=ALL;
grant drop any table to &&REPLICATION_USER CONTAINER=ALL;
grant logmining to &&REPLICATION_USER CONTAINER=ALL;
