CREATE TABLE SYNC_PROGRESS 
(
  DB_LINK VARCHAR2(30 CHAR) NOT NULL
, CONTAINER_NAME VARCHAR2(30 CHAR) NOT NULL
, SYNC_SCN number
, CONSTRAINT SYNC_PROGRESS_PK PRIMARY KEY 
  (
    DB_LINK,
	CONTAINER_NAME
  )
  ENABLE 
);
